### ISSUE TITLE
nfs_share is incompatible with PHPStorm "Project files cannot be watched"

### ISSUE THREAD

**Issue by paales** [EcomDev/fast-hypernode#4]
Do you know if there is any solution to get the nfs_share working with PHPStorm. I wanted to set this up to use this with development, but that doesn't seem possible at the moment, because code inspection is something I rely on all the time..

Ideas by any chance? Or is the unison thingy supposed to help (got build errors with the latest develop branch by the way)?

**Comment by IvanChepurnyi** [comment]
Seems like in recent version of PHP storm they have issue with NFS, so that is why I started working on Unison. It works fine for me on dev branch, would be great if you can share your experience on that build errors. Did you have unison being installed on your host? I cannot install it from the box.

**Comment by paales** [comment]
Working with unison works as expected! Thanks
